"""initial current models

Revision ID: 096651ef108d
Revises:
Create Date: 2026-09-15 23:11:27.874066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '096651ef108d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
