"""add password recovery otp flow

Revision ID: 1da9cb3da96d
Revises: 332881b6cbb9
Create Date: 2026-09-17 19:41:38.040204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '1da9cb3da96d'
down_revision: Union[str, Sequence[str], None] = '332881b6cbb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_challenges',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('identifier_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('identifier_kind', sa.String(length=20), nullable=False),
    sa.Column('purpose', sa.String(length=40), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('otp_digest', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('resend_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invalidated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reset_jti_digest', sa.String(length=64), nullable=True),
    sa.Column('reset_authorized_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_status', sa.String(length=20), server_default='pending', nullable=False),
    sa.CheckConstraint("channel IN ('email', 'sms', 'none')", name='ck_otp_challenges_channel'),
    sa.CheckConstraint("delivery_status IN ('pending', 'sent', 'suppressed', 'failed')", name='ck_otp_challenges_delivery_status'),
    sa.CheckConstraint("identifier_kind IN ('email', 'mobile', 'unknown')", name='ck_otp_challenges_identifier_kind'),
    sa.CheckConstraint("purpose = 'password_recovery'", name='ck_otp_challenges_purpose'),
    sa.CheckConstraint('attempts >= 0', name='ck_otp_challenges_attempts_nonnegative'),
    sa.CheckConstraint('resend_count >= 0', name='ck_otp_challenges_resend_count_nonnegative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_otp_challenges_user_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_otp_challenges_expires_at', 'otp_challenges', ['expires_at'], unique=False)
    op.create_index('ix_otp_challenges_identifier_purpose_created', 'otp_challenges', ['identifier_fingerprint', 'purpose', 'created_at'], unique=False)
    op.create_index('ix_otp_challenges_user_purpose_created', 'otp_challenges', ['user_id', 'purpose', 'created_at'], unique=False)
    op.create_index('uq_otp_challenges_active_identifier_purpose', 'otp_challenges', ['identifier_fingerprint', 'purpose'], unique=True, postgresql_where=sa.text('consumed_at IS NULL AND invalidated_at IS NULL'), sqlite_where=sa.text('consumed_at IS NULL AND invalidated_at IS NULL'))
    op.add_column('users', sa.Column('auth_version', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint('uq_users_student_id', 'users', ['student_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_users_student_id', 'users', type_='unique')
    op.drop_column('users', 'password_changed_at')
    op.drop_column('users', 'auth_version')
    op.drop_index('uq_otp_challenges_active_identifier_purpose', table_name='otp_challenges', postgresql_where=sa.text('consumed_at IS NULL AND invalidated_at IS NULL'), sqlite_where=sa.text('consumed_at IS NULL AND invalidated_at IS NULL'))
    op.drop_index('ix_otp_challenges_user_purpose_created', table_name='otp_challenges')
    op.drop_index('ix_otp_challenges_identifier_purpose_created', table_name='otp_challenges')
    op.drop_index('ix_otp_challenges_expires_at', table_name='otp_challenges')
    op.drop_table('otp_challenges')
    # ### end Alembic commands ###
