"""harden application integrity

Revision ID: 2027e24c37d1
Revises: 096651ef108d
Create Date: 2026-09-16 01:15:47.789792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '2027e24c37d1'
down_revision: Union[str, Sequence[str], None] = '096651ef108d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_applications_drive_id', 'applications', ['drive_id'], unique=False)
    op.create_unique_constraint('uq_applications_student_drive', 'applications', ['student_id', 'drive_id'])
    op.create_foreign_key('fk_applications_drive_id_placement_drives', 'applications', 'placement_drives', ['drive_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('fk_applications_student_id_students', 'applications', 'students', ['student_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_applications_student_id_students', 'applications', type_='foreignkey')
    op.drop_constraint('fk_applications_drive_id_placement_drives', 'applications', type_='foreignkey')
    op.drop_constraint('uq_applications_student_drive', 'applications', type_='unique')
    op.drop_index('ix_applications_drive_id', table_name='applications')
    # ### end Alembic commands ###
