"""add pwd eligibility to placement drives

Revision ID: b7dc7968babe
Revises: 2027e24c37d1
Create Date: 2026-09-16 09:24:39.545913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = 'b7dc7968babe'
down_revision: Union[str, Sequence[str], None] = '2027e24c37d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('placement_drives', sa.Column('pwd_eligibility', sa.String(length=20), server_default='Any', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('placement_drives', 'pwd_eligibility')
    # ### end Alembic commands ###
